name: Unit Tests - RSpec

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '2.5', '2.6', '2.7', '3.0' ]
    name: Ruby ${{ matrix.ruby }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install Gems
      run: bundle install
    - name: Run tests
      run: bundle exec rspec
